console.log("Typescripte girdik");
console.log("Selam");
var age = 29;
var firstName = "Saffet";
console.log(age);
console.log(firstName);
var isUpdated = true;
console.log(isUpdated);
var employeName = "Saffet";
var employeDesc = "".concat(employeName, " works well.");
console.log(employeDesc);
var isPresent = true;
console.log(isPresent);
//string array tanımlamak için kullanılan 1. yöntem;
var names = ["Saffet", "Ramazan", "Kaban"];
console.log(names);
//string array tanımlamak için kullanılan 2. yöntem;
var soyIsimler = ["Kaban", "Yıldırım", "Demirhan"];
console.log(soyIsimler);
